import { Component } from '@angular/core';
import { AngularFirestore } from '@angular/fire/compat/firestore';
import { FormControl } from '@angular/forms';
import { AngularFireStorage } from '@angular/fire/compat/storage';

import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-testing',
  templateUrl: './testing.component.html',
  styleUrls: ['./testing.component.scss']
})
export class TestingComponent {
  text = 'hola';
  lstColaboradores = [
    {
      "id": "Angela-Martinez",
      "scargo": "asistente",
      "snombre": "Angela Martinez",
      "scolor": "#B6045A",
      "spassword": "70995788",
      "lactive": true
    },
    {
      "scolor": "#171C0C",
      "snombre": "Angelly Castillo",
      "spassword": "74867199",
      "id": "Angelly-Castillo",
      "lactive": true,
      "scargo": "asistente"
    },
    {
      "scargo": "asistente",
      "scolor": "#AE30E6",
      "snombre": "Camila Arnica",
      "id": "Camila-Arnica",
      "spassword": "77910628",
      "lactive": true
    },
    {
      "snombre": "Christopher Guzman",
      "spassword": "72089198",
      "scargo": "asistente",
      "id": "Christopher-Guzman",
      "lactive": true,
      "scolor": "#2713CF"
    },
    {
      "scolor": "#0E9557",
      "scargo": "asistente",
      "snombre": "Crishtian Paucar",
      "id": "Crishtian-Paucar",
      "spassword": "48244086",
      "lactive": true
    },
    {
      "id": "Edu-Soto",
      "scolor": "#C90D52",
      "spassword": "71074369",
      "snombre": "Eduardo Soto",
      "scargo": "asistente",
      "lactive": true
    },
    {
      "scargo": "asistente",
      "snombre": "Esmeralda Aslla",
      "id": "Esmeralda-Aslla",
      "scolor": "#317657",
      "lactive": true,
      "spassword": "73004593"
    },
    {
      "scargo": "asistente",
      "snombre": "Fabiola Mayta",
      "lactive": true,
      "id": "Fabi-Mayta",
      "spassword": "76603955",
      "scolor": "#4D8FF4"
    },
    {
      "snombre": "Jenny Perez",
      "scolor": "#69BFB5",
      "scargo": "asistente",
      "spassword": "70948369",
      "lactive": true,
      "id": "Jenny-Perez"
    },
    {
      "scargo": "asistente",
      "scolor": "#D643E9",
      "snombre": "Marcos Carbajal",
      "spassword": "76590181",
      "id": "Marcos-Carbajal",
      "lactive": true
    },
    {
      "lactive": true,
      "spassword": "71318117",
      "id": "Maria-Rosado",
      "scargo": "asistente",
      "snombre": "Maria Rosado",
      "scolor": "#4377D0"
    },
    {
      "spassword": "72177542",
      "lactive": true,
      "scolor": "#866E73",
      "id": "Mil-Lazo",
      "scargo": "asistente",
      "snombre": "Mil Lazo"
    },
    {
      "scolor": "#51381E",
      "snombre": "Nicole Cardenas",
      "lactive": true,
      "id": "Nicole-Cardenas",
      "spassword": "72894325",
      "scargo": "asistente"
    },
    {
      "id": "Sebastian-Rodriguez",
      "scolor": "#7AD726",
      "spassword": "72745775",
      "scargo": "asistente",
      "lactive": true,
      "snombre": "Sebastian Rodriguez"
    },
    {
      "spassword": "75238966",
      "scolor": "#BC5CE1",
      "lactive": true,
      "scargo": "asistente",
      "snombre": "Sharon Huallpa",
      "id": "Sharon-Huallpa"
    },
    {
      "id": "Shaunny-Fernandez",
      "scargo": "asistente",
      "snombre": "Shaunny Fernandez",
      "lactive": true,
      "scolor": "#D3B1F3",
      "spassword": "72535661"
    },
    {
      "scolor": "#AAAB33",
      "snombre": "Yuliana Alvarez Calderón",
      "lactive": true,
      "spassword": "73481941",
      "scargo": "asistente",
      "id": "Yuliana-Alvarez"
    },
    {
      "snombre": "Darlene Ccasa",
      "scargo": "asistente",
      "lactive": true,
      "spassword": "75136309",
      "scolor": "#57F803",
      "id": "darlene-ccasa"
    },
    {
      "scargo": "asistente",
      "snombre": "Elmer Mamani",
      "spassword": "75711373",
      "alias": "asist",
      "id": "elmer-mamani",
      "scolor": "#38f5c5",
      "lactive": true
    },
    {
      "scargo": "asistente",
      "spassword": "70308942",
      "lactive": true,
      "id": "jannet-mendoza",
      "snombre": "Jannet Mendoza",
      "scolor": "#96823F"
    },
    {
      "scolor": "#350DB7",
      "scargo": "asistente",
      "lactive": true,
      "spassword": "73314338",
      "id": "jim-machaca",
      "snombre": "jimena machaca"
    },
    {
      "alias": "dra-lizbet",
      "lactive": true,
      "snombre": "Lizbet Silva Guillén",
      "scargo": "abogado",
      "sCargo": "Abogado",
      "spassword": "lizbet-silva123",
      "scolor": "#ff0000",
      "id": "lizbet-silva"
    }
  ];
  lstRdts = [
    {
      "nfecha": 1733840728424,
      "nsemana": 50,
      "idrdt": "2024-12-10-Angela-Martinez",
      "idcolaborador": "Angela-Martinez",
      "shorasalida": "16",
      "sminutoingreso": "50",
      "scolaborador": "Angela Martinez",
      "shoraingreso": "07",
      "sfecha": "2024-12-10",
      "ndia": 345,
      "leditable": true,
      "sminutosalida": "46"
    },
    {
      "sfecha": "2024-12-10",
      "shorasalida": "13",
      "nfecha": 1733840728424,
      "sminutosalida": "22",
      "sminutoingreso": "13",
      "shoraingreso": "09",
      "idcolaborador": "Angelly-Castillo",
      "ndia": 345,
      "idrdt": "2024-12-10-Angelly-Castillo",
      "leditable": true,
      "scolaborador": "Angelly Castillo",
      "nsemana": 50
    },
    {
      "sfecha": "2024-12-10",
      "leditable": true,
      "sminutosalida": "--",
      "idrdt": "2024-12-10-Camila-Arnica",
      "scolaborador": "Camila Arnica",
      "sminutoingreso": "--",
      "nfecha": 1733840728424,
      "shorasalida": "--",
      "ndia": 345,
      "idcolaborador": "Camila-Arnica",
      "shoraingreso": "--",
      "nsemana": 50
    },
    {
      "scolaborador": "Christopher Guzman",
      "sfecha": "2024-12-10",
      "shoraingreso": "08",
      "leditable": true,
      "nfecha": 1733840728424,
      "shorasalida": "13",
      "ndia": 345,
      "idrdt": "2024-12-10-Christopher-Guzman",
      "nsemana": 50,
      "sminutoingreso": "07",
      "sminutosalida": "41",
      "idcolaborador": "Christopher-Guzman"
    },
    {
      "shorasalida": "17",
      "sfecha": "2024-12-10",
      "leditable": true,
      "idcolaborador": "Crishtian-Paucar",
      "sminutosalida": "27",
      "ndia": 345,
      "shoraingreso": "08",
      "nfecha": 1733840728424,
      "nsemana": 50,
      "sminutoingreso": "11",
      "scolaborador": "Crishtian Paucar",
      "idrdt": "2024-12-10-Crishtian-Paucar"
    },
    {
      "shoraingreso": "08",
      "scolaborador": "Eduardo Soto",
      "leditable": true,
      "idcolaborador": "Edu-Soto",
      "nfecha": 1733840728424,
      "sminutoingreso": "11",
      "ndia": 345,
      "sminutosalida": "24",
      "nsemana": 50,
      "sfecha": "2024-12-10",
      "idrdt": "2024-12-10-Edu-Soto",
      "shorasalida": "16"
    },
    {
      "leditable": true,
      "shoraingreso": "08",
      "scolaborador": "Esmeralda Aslla",
      "idcolaborador": "Esmeralda-Aslla",
      "sfecha": "2024-12-10",
      "nsemana": 50,
      "nfecha": 1733840728424,
      "idrdt": "2024-12-10-Esmeralda-Aslla",
      "sminutosalida": "06",
      "shorasalida": "16",
      "sminutoingreso": "42",
      "ndia": 345
    },
    {
      "shoraingreso": "15",
      "idcolaborador": "Fabi-Mayta",
      "leditable": true,
      "sminutoingreso": "24",
      "sfecha": "2024-12-10",
      "nsemana": 50,
      "sminutosalida": "26",
      "idrdt": "2024-12-10-Fabi-Mayta",
      "ndia": 345,
      "shorasalida": "19",
      "scolaborador": "Fabiola Mayta",
      "nfecha": 1733840728424
    },
    {
      "idcolaborador": "Jean-Calderon",
      "idrdt": "2024-12-10-Jean-Calderon",
      "sfecha": "2024-12-10",
      "ndia": 345,
      "scolaborador": "Jean Marco Calderon",
      "sminutosalida": "45",
      "nfecha": 1733840728424,
      "nsemana": 50,
      "shorasalida": "16",
      "leditable": true,
      "sminutoingreso": "53",
      "shoraingreso": "07"
    },
    {
      "sminutoingreso": "09",
      "shoraingreso": "08",
      "idcolaborador": "Jenny-Perez",
      "nsemana": 50,
      "ndia": 345,
      "idrdt": "2024-12-10-Jenny-Perez",
      "sminutosalida": "58",
      "leditable": true,
      "sfecha": "2024-12-10",
      "scolaborador": "Jenny Perez",
      "nfecha": 1733840728424,
      "shorasalida": "16"
    },
    {
      "idcolaborador": "Marcos-Carbajal",
      "idrdt": "2024-12-10-Marcos-Carbajal",
      "sminutosalida": "15",
      "shorasalida": "17",
      "leditable": true,
      "shoraingreso": "08",
      "scolaborador": "Marcos Carbajal",
      "sfecha": "2024-12-10",
      "ndia": 345,
      "nfecha": 1733840728424,
      "sminutoingreso": "19",
      "nsemana": 50
    },
    {
      "idrdt": "2024-12-10-Maria-Rosado",
      "sminutoingreso": "--",
      "shoraingreso": "--",
      "nfecha": 1733840728424,
      "sfecha": "2024-12-10",
      "nsemana": 50,
      "shorasalida": "--",
      "leditable": true,
      "sminutosalida": "--",
      "idcolaborador": "Maria-Rosado",
      "scolaborador": "Maria Rosado",
      "ndia": 345
    },
    {
      "idrdt": "2024-12-10-Mariafe-Corrales",
      "shorasalida": "--",
      "nfecha": 1733840728424,
      "ndia": 345,
      "sfecha": "2024-12-10",
      "shoraingreso": "--",
      "sminutosalida": "--",
      "nsemana": 50,
      "leditable": true,
      "scolaborador": "Mariafe Corrales",
      "idcolaborador": "Mariafe-Corrales",
      "sminutoingreso": "--"
    },
    {
      "shorasalida": "11",
      "sfecha": "2024-12-10",
      "nfecha": 1733840728424,
      "leditable": true,
      "shoraingreso": "08",
      "ndia": 345,
      "idcolaborador": "Mil-Lazo",
      "scolaborador": "Mil Lazo",
      "sminutoingreso": "48",
      "idrdt": "2024-12-10-Mil-Lazo",
      "nsemana": 50,
      "sminutosalida": "38"
    },
    {
      "scolaborador": "Nicole Cardenas",
      "sminutosalida": "09",
      "idrdt": "2024-12-10-Nicole-Cardenas",
      "shoraingreso": "08",
      "sfecha": "2024-12-10",
      "nfecha": 1733840728424,
      "sminutoingreso": "01",
      "leditable": true,
      "idcolaborador": "Nicole-Cardenas",
      "nsemana": 50,
      "ndia": 345,
      "shorasalida": "17"
    },
    {
      "idrdt": "2024-12-10-Sebastian-Rodriguez",
      "sminutoingreso": "50",
      "sfecha": "2024-12-10",
      "idcolaborador": "Sebastian-Rodriguez",
      "sminutosalida": "23",
      "shoraingreso": "07",
      "leditable": true,
      "nsemana": 50,
      "scolaborador": "Sebastian Rodriguez",
      "shorasalida": "15",
      "ndia": 345,
      "nfecha": 1733840728424
    },
    {
      "sfecha": "2024-12-10",
      "nsemana": 50,
      "idrdt": "2024-12-10-Sharon-Huallpa",
      "idcolaborador": "Sharon-Huallpa",
      "shoraingreso": "07",
      "sminutoingreso": "57",
      "scolaborador": "Sharon Huallpa",
      "ndia": 345,
      "sminutosalida": "16",
      "shorasalida": "17",
      "nfecha": 1733840728424,
      "leditable": true
    },
    {
      "shoraingreso": "07",
      "sminutoingreso": "54",
      "idrdt": "2024-12-10-Shaunny-Fernandez",
      "ndia": 345,
      "sminutosalida": "47",
      "leditable": true,
      "shorasalida": "16",
      "idcolaborador": "Shaunny-Fernandez",
      "sfecha": "2024-12-10",
      "nsemana": 50,
      "nfecha": 1733840728424,
      "scolaborador": "Shaunny Fernandez"
    },
    {
      "ndia": 345,
      "sfecha": "2024-12-10",
      "shorasalida": "12",
      "nsemana": 50,
      "shoraingreso": "08",
      "sminutosalida": "00",
      "sminutoingreso": "19",
      "scolaborador": "Yuliana Alvarez Calderón",
      "nfecha": 1733840728424,
      "leditable": true,
      "idcolaborador": "Yuliana-Alvarez",
      "idrdt": "2024-12-10-Yuliana-Alvarez"
    },
    {
      "shorasalida": "17",
      "sminutosalida": "08",
      "leditable": true,
      "scolaborador": "Darlene Ccasa",
      "nfecha": 1733840728424,
      "idcolaborador": "darlene-ccasa",
      "sminutoingreso": "53",
      "ndia": 345,
      "shoraingreso": "12",
      "idrdt": "2024-12-10-darlene-ccasa",
      "nsemana": 50,
      "sfecha": "2024-12-10"
    },
    {
      "nsemana": 50,
      "scolaborador": "Elmer Mamani",
      "ndia": 345,
      "sminutoingreso": "27",
      "sminutosalida": "08",
      "sfecha": "2024-12-10",
      "shoraingreso": "08",
      "idcolaborador": "elmer-mamani",
      "nfecha": 1733840728424,
      "shorasalida": "13",
      "idrdt": "2024-12-10-elmer-mamani",
      "leditable": true
    },
    {
      "sminutosalida": "30",
      "scolaborador": "Jannet Mendoza",
      "sfecha": "2024-12-10",
      "nsemana": 50,
      "nfecha": 1733840728424,
      "shorasalida": "13",
      "sminutoingreso": "50",
      "shoraingreso": "07",
      "idrdt": "2024-12-10-jannet-mendoza",
      "idcolaborador": "jannet-mendoza",
      "ndia": 345,
      "leditable": true
    },
    {
      "nfecha": 1733840728424,
      "shoraingreso": "07",
      "sfecha": "2024-12-10",
      "shorasalida": "17",
      "nsemana": 50,
      "sminutosalida": "16",
      "idrdt": "2024-12-10-jim-machaca",
      "idcolaborador": "jim-machaca",
      "scolaborador": "jimena machaca",
      "ndia": 345,
      "sminutoingreso": "50",
      "leditable": true
    },
    {
      "idrdt": "2024-12-10-lizbet-silva",
      "ndia": 345,
      "idcolaborador": "lizbet-silva",
      "nsemana": 50,
      "leditable": true,
      "scolaborador": "Lizbet Silva Guillén",
      "sfecha": "2024-12-10",
      "shorasalida": "17",
      "sminutoingreso": "58",
      "nfecha": 1733840728424,
      "shoraingreso": "07",
      "sminutosalida": "20"
    },
    {
      "idrdt": "2024-12-11-Angela-Martinez",
      "shoraingreso": "07",
      "ndia": 346,
      "shorasalida": "16",
      "scolaborador": "Angela Martinez",
      "nsemana": 50,
      "sfecha": "2024-12-11",
      "idcolaborador": "Angela-Martinez",
      "nfecha": 1733924206698,
      "sminutosalida": "57",
      "sminutoingreso": "56",
      "leditable": true
    },
    {
      "nfecha": 1733924206698,
      "sfecha": "2024-12-11",
      "sminutoingreso": "58",
      "idcolaborador": "Angelly-Castillo",
      "sminutosalida": "12",
      "shoraingreso": "07",
      "leditable": true,
      "idrdt": "2024-12-11-Angelly-Castillo",
      "shorasalida": "13",
      "nsemana": 50,
      "ndia": 346,
      "scolaborador": "Angelly Castillo"
    },
    {
      "idcolaborador": "Camila-Arnica",
      "scolaborador": "Camila Arnica",
      "shorasalida": "17",
      "nfecha": 1733924206698,
      "idrdt": "2024-12-11-Camila-Arnica",
      "sminutosalida": "40",
      "sfecha": "2024-12-11",
      "shoraingreso": "12",
      "nsemana": 50,
      "sminutoingreso": "55",
      "ndia": 346,
      "leditable": true
    },
    {
      "nsemana": 50,
      "sfecha": "2024-12-11",
      "sminutosalida": "--",
      "sminutoingreso": "--",
      "scolaborador": "Christopher Guzman",
      "leditable": true,
      "ndia": 346,
      "idrdt": "2024-12-11-Christopher-Guzman",
      "idcolaborador": "Christopher-Guzman",
      "shoraingreso": "--",
      "shorasalida": "--",
      "nfecha": 1733924206698
    },
    {
      "scolaborador": "Crishtian Paucar",
      "shoraingreso": "08",
      "idcolaborador": "Crishtian-Paucar",
      "sminutoingreso": "28",
      "idrdt": "2024-12-11-Crishtian-Paucar",
      "ndia": 346,
      "sfecha": "2024-12-11",
      "sminutosalida": "51",
      "nfecha": 1733924206698,
      "leditable": true,
      "shorasalida": "17",
      "nsemana": 50
    },
    {
      "scolaborador": "Eduardo Soto",
      "leditable": true,
      "shoraingreso": "07",
      "ndia": 346,
      "idrdt": "2024-12-11-Edu-Soto",
      "idcolaborador": "Edu-Soto",
      "sminutosalida": "50",
      "sminutoingreso": "53",
      "sfecha": "2024-12-11",
      "shorasalida": "16",
      "nfecha": 1733924206698,
      "nsemana": 50
    },
    {
      "idcolaborador": "Esmeralda-Aslla",
      "ndia": 346,
      "idrdt": "2024-12-11-Esmeralda-Aslla",
      "shorasalida": "--",
      "scolaborador": "Esmeralda Aslla",
      "sminutosalida": "--",
      "sfecha": "2024-12-11",
      "leditable": true,
      "sminutoingreso": "--",
      "shoraingreso": "--",
      "nfecha": 1733924206698,
      "nsemana": 50
    },
    {
      "idcolaborador": "Fabi-Mayta",
      "shoraingreso": "14",
      "ndia": 346,
      "scolaborador": "Fabiola Mayta",
      "sfecha": "2024-12-11",
      "leditable": true,
      "nfecha": 1733924206698,
      "idrdt": "2024-12-11-Fabi-Mayta",
      "shorasalida": "18",
      "nsemana": 50,
      "sminutosalida": "54",
      "sminutoingreso": "50"
    },
    {
      "leditable": true,
      "shoraingreso": "12",
      "nfecha": 1733924206698,
      "idcolaborador": "Jean-Calderon",
      "idrdt": "2024-12-11-Jean-Calderon",
      "shorasalida": "16",
      "scolaborador": "Jean Marco Calderon",
      "sminutoingreso": "44",
      "ndia": 346,
      "sminutosalida": "33",
      "nsemana": 50,
      "sfecha": "2024-12-11"
    },
    {
      "shorasalida": "13",
      "sfecha": "2024-12-11",
      "sminutosalida": "39",
      "idcolaborador": "Jenny-Perez",
      "nsemana": 50,
      "sminutoingreso": "59",
      "leditable": true,
      "idrdt": "2024-12-11-Jenny-Perez",
      "scolaborador": "Jenny Perez",
      "shoraingreso": "07",
      "nfecha": 1733924206698,
      "ndia": 346
    },
    {
      "shoraingreso": "--",
      "ndia": 346,
      "idrdt": "2024-12-11-Marcos-Carbajal",
      "idcolaborador": "Marcos-Carbajal",
      "nsemana": 50,
      "sfecha": "2024-12-11",
      "sminutosalida": "--",
      "sminutoingreso": "--",
      "shorasalida": "--",
      "scolaborador": "Marcos Carbajal",
      "leditable": true,
      "nfecha": 1733924206698
    },
    {
      "shorasalida": "17",
      "nfecha": 1733924206698,
      "scolaborador": "Maria Rosado",
      "ndia": 346,
      "leditable": true,
      "sminutoingreso": "04",
      "sminutosalida": "50",
      "idrdt": "2024-12-11-Maria-Rosado",
      "sfecha": "2024-12-11",
      "idcolaborador": "Maria-Rosado",
      "shoraingreso": "08",
      "nsemana": 50
    },
    {
      "sminutoingreso": "--",
      "leditable": true,
      "shoraingreso": "--",
      "shorasalida": "--",
      "sminutosalida": "--",
      "nsemana": 50,
      "ndia": 346,
      "nfecha": 1733924206698,
      "sfecha": "2024-12-11",
      "idcolaborador": "Mariafe-Corrales",
      "scolaborador": "Mariafe Corrales",
      "idrdt": "2024-12-11-Mariafe-Corrales"
    },
    {
      "sfecha": "2024-12-11",
      "idrdt": "2024-12-11-Mil-Lazo",
      "shoraingreso": "08",
      "idcolaborador": "Mil-Lazo",
      "nsemana": 50,
      "nfecha": 1733924206698,
      "sminutosalida": "33",
      "scolaborador": "Mil Lazo",
      "sminutoingreso": "53",
      "leditable": true,
      "ndia": 346,
      "shorasalida": "17"
    },
    {
      "shoraingreso": "08",
      "sfecha": "2024-12-11",
      "idcolaborador": "Nicole-Cardenas",
      "leditable": true,
      "idrdt": "2024-12-11-Nicole-Cardenas",
      "ndia": 346,
      "sminutoingreso": "07",
      "nsemana": 50,
      "scolaborador": "Nicole Cardenas",
      "shorasalida": "17",
      "nfecha": 1733924206698,
      "sminutosalida": "21"
    },
    {
      "sfecha": "2024-12-11",
      "leditable": true,
      "scolaborador": "Sebastian Rodriguez",
      "idrdt": "2024-12-11-Sebastian-Rodriguez",
      "nsemana": 50,
      "sminutosalida": "54",
      "shorasalida": "16",
      "idcolaborador": "Sebastian-Rodriguez",
      "ndia": 346,
      "sminutoingreso": "27",
      "shoraingreso": "09",
      "nfecha": 1733924206698
    },
    {
      "nfecha": 1733924206698,
      "idrdt": "2024-12-11-Sharon-Huallpa",
      "ndia": 346,
      "sminutosalida": "36",
      "shoraingreso": "07",
      "nsemana": 50,
      "sminutoingreso": "39",
      "shorasalida": "17",
      "scolaborador": "Sharon Huallpa",
      "leditable": true,
      "idcolaborador": "Sharon-Huallpa",
      "sfecha": "2024-12-11"
    },
    {
      "leditable": true,
      "ndia": 346,
      "shorasalida": "16",
      "sminutoingreso": "58",
      "sminutosalida": "16",
      "idcolaborador": "Shaunny-Fernandez",
      "scolaborador": "Shaunny Fernandez",
      "shoraingreso": "07",
      "nsemana": 50,
      "idrdt": "2024-12-11-Shaunny-Fernandez",
      "nfecha": 1733924206698,
      "sfecha": "2024-12-11"
    },
    {
      "idrdt": "2024-12-11-Yuliana-Alvarez",
      "nfecha": 1733924206698,
      "scolaborador": "Yuliana Alvarez Calderón",
      "shoraingreso": "08",
      "shorasalida": "12",
      "sfecha": "2024-12-11",
      "ndia": 346,
      "nsemana": 50,
      "idcolaborador": "Yuliana-Alvarez",
      "sminutoingreso": "00",
      "sminutosalida": "00",
      "leditable": true
    },
    {
      "sfecha": "2024-12-11",
      "idcolaborador": "darlene-ccasa",
      "sminutosalida": "13",
      "nfecha": 1733924206698,
      "shoraingreso": "12",
      "idrdt": "2024-12-11-darlene-ccasa",
      "sminutoingreso": "59",
      "scolaborador": "Darlene Ccasa",
      "leditable": true,
      "nsemana": 50,
      "ndia": 346,
      "shorasalida": "17"
    },
    {
      "nfecha": 1733924206698,
      "sminutoingreso": "15",
      "nsemana": 50,
      "leditable": true,
      "ndia": 346,
      "sminutosalida": "14",
      "shorasalida": "13",
      "idrdt": "2024-12-11-elmer-mamani",
      "scolaborador": "Elmer Mamani",
      "idcolaborador": "elmer-mamani",
      "sfecha": "2024-12-11",
      "shoraingreso": "08"
    },
    {
      "sfecha": "2024-12-11",
      "sminutosalida": "52",
      "sminutoingreso": "37",
      "nfecha": 1733924206698,
      "idcolaborador": "jannet-mendoza",
      "idrdt": "2024-12-11-jannet-mendoza",
      "scolaborador": "Jannet Mendoza",
      "shoraingreso": "07",
      "shorasalida": "13",
      "leditable": true,
      "ndia": 346,
      "nsemana": 50
    },
    {
      "sminutosalida": "51",
      "sminutoingreso": "26",
      "leditable": true,
      "ndia": 346,
      "shorasalida": "16",
      "nfecha": 1733924206698,
      "idrdt": "2024-12-11-jim-machaca",
      "sfecha": "2024-12-11",
      "nsemana": 50,
      "shoraingreso": "07",
      "idcolaborador": "jim-machaca",
      "scolaborador": "jimena machaca"
    },
    {
      "nfecha": 1733924206698,
      "scolaborador": "Lizbet Silva Guillén",
      "ndia": 346,
      "nsemana": 50,
      "sminutosalida": "58",
      "shorasalida": "17",
      "idrdt": "2024-12-11-lizbet-silva",
      "leditable": true,
      "sminutoingreso": "48",
      "sfecha": "2024-12-11",
      "shoraingreso": "07",
      "idcolaborador": "lizbet-silva"
    },
    {
      "shoraingreso": "07",
      "idrdt": "2024-12-12-Angela-Martinez",
      "shorasalida": "16",
      "nfecha": 1734010445592,
      "sminutoingreso": "56",
      "leditable": true,
      "idcolaborador": "Angela-Martinez",
      "nsemana": 50,
      "sminutosalida": "57",
      "ndia": 347,
      "sfecha": "2024-12-12",
      "scolaborador": "Angela Martinez"
    },
    {
      "ndia": 347,
      "sminutoingreso": "--",
      "nsemana": 50,
      "idrdt": "2024-12-12-Angelly-Castillo",
      "sminutosalida": "--",
      "sfecha": "2024-12-12",
      "scolaborador": "Angelly Castillo",
      "leditable": true,
      "nfecha": 1734010445592,
      "shoraingreso": "--",
      "shorasalida": "--",
      "idcolaborador": "Angelly-Castillo"
    },
    {
      "idcolaborador": "Camila-Arnica",
      "shorasalida": "--",
      "shoraingreso": "--",
      "sminutosalida": "--",
      "ndia": 347,
      "nsemana": 50,
      "scolaborador": "Camila Arnica",
      "leditable": true,
      "idrdt": "2024-12-12-Camila-Arnica",
      "nfecha": 1734010445592,
      "sfecha": "2024-12-12",
      "sminutoingreso": "--"
    },
    {
      "idcolaborador": "Christopher-Guzman",
      "leditable": true,
      "shorasalida": "14",
      "idrdt": "2024-12-12-Christopher-Guzman",
      "shoraingreso": "08",
      "sminutosalida": "20",
      "nsemana": 50,
      "ndia": 347,
      "sfecha": "2024-12-12",
      "nfecha": 1734010445592,
      "scolaborador": "Christopher Guzman",
      "sminutoingreso": "03"
    },
    {
      "sminutosalida": "17",
      "sfecha": "2024-12-12",
      "nfecha": 1734010445592,
      "ndia": 347,
      "shoraingreso": "08",
      "leditable": true,
      "idrdt": "2024-12-12-Crishtian-Paucar",
      "sminutoingreso": "15",
      "idcolaborador": "Crishtian-Paucar",
      "nsemana": 50,
      "shorasalida": "17",
      "scolaborador": "Crishtian Paucar"
    },
    {
      "sminutosalida": "33",
      "sminutoingreso": "58",
      "nfecha": 1734010445592,
      "idcolaborador": "Edu-Soto",
      "leditable": true,
      "shorasalida": "18",
      "nsemana": 50,
      "idrdt": "2024-12-12-Edu-Soto",
      "sfecha": "2024-12-12",
      "shoraingreso": "07",
      "ndia": 347,
      "scolaborador": "Eduardo Soto"
    },
    {
      "sfecha": "2024-12-12",
      "idrdt": "2024-12-12-Esmeralda-Aslla",
      "leditable": true,
      "nfecha": 1734010445592,
      "ndia": 347,
      "sminutoingreso": "07",
      "scolaborador": "Esmeralda Aslla",
      "idcolaborador": "Esmeralda-Aslla",
      "shoraingreso": "09",
      "sminutosalida": "25",
      "shorasalida": "16",
      "nsemana": 50
    },
    {
      "leditable": true,
      "idrdt": "2024-12-12-Fabi-Mayta",
      "sfecha": "2024-12-12",
      "sminutoingreso": "48",
      "sminutosalida": "55",
      "nsemana": 50,
      "scolaborador": "Fabiola Mayta",
      "shoraingreso": "15",
      "nfecha": 1734010445592,
      "idcolaborador": "Fabi-Mayta",
      "ndia": 347,
      "shorasalida": "19"
    },
    {
      "nsemana": 50,
      "scolaborador": "Jenny Perez",
      "leditable": true,
      "sminutosalida": "39",
      "ndia": 347,
      "sfecha": "2024-12-12",
      "idcolaborador": "Jenny-Perez",
      "shorasalida": "14",
      "idrdt": "2024-12-12-Jenny-Perez",
      "sminutoingreso": "56",
      "nfecha": 1734010445592,
      "shoraingreso": "07"
    },
    {
      "idcolaborador": "Marcos-Carbajal",
      "sminutosalida": "03",
      "nfecha": 1734010445592,
      "scolaborador": "Marcos Carbajal",
      "idrdt": "2024-12-12-Marcos-Carbajal",
      "ndia": 347,
      "shorasalida": "17",
      "leditable": true,
      "shoraingreso": "08",
      "nsemana": 50,
      "sfecha": "2024-12-12",
      "sminutoingreso": "09"
    },
    {
      "nsemana": 50,
      "leditable": true,
      "sminutoingreso": "28",
      "idrdt": "2024-12-12-Maria-Rosado",
      "ndia": 347,
      "shoraingreso": "08",
      "nfecha": 1734010445592,
      "sminutosalida": "01",
      "shorasalida": "17",
      "idcolaborador": "Maria-Rosado",
      "sfecha": "2024-12-12",
      "scolaborador": "Maria Rosado"
    },
    {
      "sminutoingreso": "59",
      "sminutosalida": "30",
      "shoraingreso": "08",
      "ndia": 347,
      "shorasalida": "18",
      "idrdt": "2024-12-12-Mil-Lazo",
      "idcolaborador": "Mil-Lazo",
      "leditable": true,
      "nfecha": 1734010445592,
      "scolaborador": "Mil Lazo",
      "sfecha": "2024-12-12",
      "nsemana": 50
    },
    {
      "nfecha": 1734010445592,
      "idcolaborador": "Nicole-Cardenas",
      "ndia": 347,
      "sfecha": "2024-12-12",
      "idrdt": "2024-12-12-Nicole-Cardenas",
      "leditable": true,
      "scolaborador": "Nicole Cardenas",
      "shoraingreso": "08",
      "shorasalida": "18",
      "sminutoingreso": "12",
      "sminutosalida": "01",
      "nsemana": 50
    },
    {
      "sfecha": "2024-12-12",
      "idrdt": "2024-12-12-Sebastian-Rodriguez",
      "idcolaborador": "Sebastian-Rodriguez",
      "sminutosalida": "00",
      "scolaborador": "Sebastian Rodriguez",
      "leditable": true,
      "ndia": 347,
      "shorasalida": "16",
      "nfecha": 1734010445592,
      "shoraingreso": "07",
      "sminutoingreso": "56",
      "nsemana": 50
    },
    {
      "scolaborador": "Sharon Huallpa",
      "leditable": true,
      "sfecha": "2024-12-12",
      "idrdt": "2024-12-12-Sharon-Huallpa",
      "sminutosalida": "08",
      "sminutoingreso": "55",
      "nsemana": 50,
      "ndia": 347,
      "idcolaborador": "Sharon-Huallpa",
      "nfecha": 1734010445592,
      "shoraingreso": "07",
      "shorasalida": "17"
    },
    {
      "sminutoingreso": "57",
      "ndia": 347,
      "scolaborador": "Shaunny Fernandez",
      "idrdt": "2024-12-12-Shaunny-Fernandez",
      "sminutosalida": "48",
      "leditable": true,
      "sfecha": "2024-12-12",
      "shorasalida": "16",
      "nfecha": 1734010445592,
      "shoraingreso": "07",
      "idcolaborador": "Shaunny-Fernandez",
      "nsemana": 50
    },
    {
      "sfecha": "2024-12-12",
      "scolaborador": "Yuliana Alvarez Calderón",
      "ndia": 347,
      "idrdt": "2024-12-12-Yuliana-Alvarez",
      "nsemana": 50,
      "leditable": true,
      "shorasalida": "--",
      "shoraingreso": "--",
      "nfecha": 1734010445592,
      "sminutoingreso": "--",
      "sminutosalida": "--",
      "idcolaborador": "Yuliana-Alvarez"
    },
    {
      "idcolaborador": "darlene-ccasa",
      "sminutosalida": "--",
      "nsemana": 50,
      "idrdt": "2024-12-12-darlene-ccasa",
      "shoraingreso": "--",
      "sfecha": "2024-12-12",
      "nfecha": 1734010445592,
      "ndia": 347,
      "shorasalida": "--",
      "sminutoingreso": "--",
      "scolaborador": "Darlene Ccasa",
      "leditable": true
    },
    {
      "shoraingreso": "08",
      "nfecha": 1734010445592,
      "sminutosalida": "31",
      "nsemana": 50,
      "idrdt": "2024-12-12-elmer-mamani",
      "leditable": true,
      "shorasalida": "13",
      "sfecha": "2024-12-12",
      "idcolaborador": "elmer-mamani",
      "sminutoingreso": "00",
      "ndia": 347,
      "scolaborador": "Elmer Mamani"
    },
    {
      "nfecha": 1734010445592,
      "leditable": true,
      "sminutosalida": "56",
      "sfecha": "2024-12-12",
      "nsemana": 50,
      "scolaborador": "Jannet Mendoza",
      "shorasalida": "13",
      "shoraingreso": "07",
      "ndia": 347,
      "sminutoingreso": "55",
      "idcolaborador": "jannet-mendoza",
      "idrdt": "2024-12-12-jannet-mendoza"
    },
    {
      "ndia": 347,
      "idrdt": "2024-12-12-jim-machaca",
      "shorasalida": "16",
      "scolaborador": "jimena machaca",
      "sfecha": "2024-12-12",
      "nsemana": 50,
      "idcolaborador": "jim-machaca",
      "sminutosalida": "56",
      "sminutoingreso": "55",
      "shoraingreso": "07",
      "nfecha": 1734010445592,
      "leditable": true
    },
    {
      "idrdt": "2024-12-12-lizbet-silva",
      "nsemana": 50,
      "sminutoingreso": "00",
      "idcolaborador": "lizbet-silva",
      "nfecha": 1734010445592,
      "shorasalida": "19",
      "sfecha": "2024-12-12",
      "scolaborador": "Lizbet Silva Guillén",
      "shoraingreso": "08",
      "ndia": 347,
      "leditable": true,
      "sminutosalida": "15"
    },
    {
      "sminutosalida": "45",
      "scolaborador": "Angela Martinez",
      "sminutoingreso": "56",
      "sfecha": "2024-12-13",
      "nsemana": 50,
      "shoraingreso": "07",
      "nfecha": 1734095489204,
      "leditable": true,
      "idrdt": "2024-12-13-Angela-Martinez",
      "idcolaborador": "Angela-Martinez",
      "shorasalida": "16",
      "ndia": 348
    },
    {
      "idcolaborador": "Angelly-Castillo",
      "shorasalida": "14",
      "sfecha": "2024-12-13",
      "shoraingreso": "07",
      "leditable": true,
      "idrdt": "2024-12-13-Angelly-Castillo",
      "nfecha": 1734095489204,
      "nsemana": 50,
      "scolaborador": "Angelly Castillo",
      "sminutosalida": "23",
      "ndia": 348,
      "sminutoingreso": "59"
    },
    {
      "idcolaborador": "Camila-Arnica",
      "sfecha": "2024-12-13",
      "idrdt": "2024-12-13-Camila-Arnica",
      "sminutosalida": "53",
      "leditable": true,
      "nsemana": 50,
      "sminutoingreso": "40",
      "shorasalida": "17",
      "ndia": 348,
      "scolaborador": "Camila Arnica",
      "shoraingreso": "12",
      "nfecha": 1734095489204
    },
    {
      "sminutosalida": "13",
      "shorasalida": "14",
      "sminutoingreso": "06",
      "idrdt": "2024-12-13-Christopher-Guzman",
      "idcolaborador": "Christopher-Guzman",
      "leditable": true,
      "nfecha": 1734095489204,
      "scolaborador": "Christopher Guzman",
      "ndia": 348,
      "sfecha": "2024-12-13",
      "nsemana": 50,
      "shoraingreso": "08"
    },
    {
      "nsemana": 50,
      "scolaborador": "Crishtian Paucar",
      "idrdt": "2024-12-13-Crishtian-Paucar",
      "shoraingreso": "08",
      "nfecha": 1734095489204,
      "sminutoingreso": "00",
      "shorasalida": "16",
      "sfecha": "2024-12-13",
      "idcolaborador": "Crishtian-Paucar",
      "sminutosalida": "44",
      "ndia": 348,
      "leditable": true
    },
    {
      "idrdt": "2024-12-13-Edu-Soto",
      "scolaborador": "Eduardo Soto",
      "shorasalida": "17",
      "idcolaborador": "Edu-Soto",
      "sminutosalida": "46",
      "nsemana": 50,
      "shoraingreso": "07",
      "nfecha": 1734095489204,
      "sfecha": "2024-12-13",
      "sminutoingreso": "40",
      "leditable": true,
      "ndia": 348
    },
    {
      "sminutosalida": "33",
      "sfecha": "2024-12-13",
      "scolaborador": "Esmeralda Aslla",
      "ndia": 348,
      "nfecha": 1734095489204,
      "nsemana": 50,
      "shoraingreso": "09",
      "idrdt": "2024-12-13-Esmeralda-Aslla",
      "idcolaborador": "Esmeralda-Aslla",
      "shorasalida": "16",
      "sminutoingreso": "06",
      "leditable": true
    },
    {
      "sminutosalida": "07",
      "scolaborador": "Fabiola Mayta",
      "idcolaborador": "Fabi-Mayta",
      "ndia": 348,
      "sfecha": "2024-12-13",
      "shorasalida": "19",
      "sminutoingreso": "00",
      "nfecha": 1734095489204,
      "leditable": true,
      "idrdt": "2024-12-13-Fabi-Mayta",
      "nsemana": 50,
      "shoraingreso": "15"
    },
    {
      "sminutoingreso": "06",
      "shoraingreso": "08",
      "nfecha": 1734095489204,
      "scolaborador": "Jenny Perez",
      "nsemana": 50,
      "idrdt": "2024-12-13-Jenny-Perez",
      "idcolaborador": "Jenny-Perez",
      "sminutosalida": "38",
      "sfecha": "2024-12-13",
      "leditable": true,
      "ndia": 348,
      "shorasalida": "13"
    },
    {
      "sminutosalida": "02",
      "sminutoingreso": "00",
      "idcolaborador": "Marcos-Carbajal",
      "nfecha": 1734095489204,
      "shorasalida": "17",
      "leditable": true,
      "scolaborador": "Marcos Carbajal",
      "idrdt": "2024-12-13-Marcos-Carbajal",
      "ndia": 348,
      "nsemana": 50,
      "sfecha": "2024-12-13",
      "shoraingreso": "08"
    },
    {
      "leditable": true,
      "scolaborador": "Maria Rosado",
      "sminutoingreso": "26",
      "nfecha": 1734095489204,
      "shoraingreso": "08",
      "shorasalida": "17",
      "ndia": 348,
      "nsemana": 50,
      "sminutosalida": "15",
      "idrdt": "2024-12-13-Maria-Rosado",
      "idcolaborador": "Maria-Rosado",
      "sfecha": "2024-12-13"
    },
    {
      "nfecha": 1734095489204,
      "ndia": 348,
      "idrdt": "2024-12-13-Mil-Lazo",
      "scolaborador": "Mil Lazo",
      "sfecha": "2024-12-13",
      "sminutosalida": "34",
      "shoraingreso": "08",
      "shorasalida": "16",
      "nsemana": 50,
      "idcolaborador": "Mil-Lazo",
      "leditable": true,
      "sminutoingreso": "13"
    },
    {
      "nfecha": 1734095489204,
      "sfecha": "2024-12-13",
      "idrdt": "2024-12-13-Nicole-Cardenas",
      "ndia": 348,
      "sminutoingreso": "13",
      "shorasalida": "17",
      "idcolaborador": "Nicole-Cardenas",
      "scolaborador": "Nicole Cardenas",
      "sminutosalida": "06",
      "leditable": true,
      "shoraingreso": "08",
      "nsemana": 50
    },
    {
      "idcolaborador": "Sebastian-Rodriguez",
      "sminutoingreso": "40",
      "leditable": true,
      "nsemana": 50,
      "sfecha": "2024-12-13",
      "nfecha": 1734095489204,
      "scolaborador": "Sebastian Rodriguez",
      "shoraingreso": "07",
      "ndia": 348,
      "shorasalida": "17",
      "idrdt": "2024-12-13-Sebastian-Rodriguez",
      "sminutosalida": "04"
    },
    {
      "sfecha": "2024-12-13",
      "ndia": 348,
      "sminutoingreso": "56",
      "leditable": true,
      "nsemana": 50,
      "shorasalida": "17",
      "shoraingreso": "07",
      "idcolaborador": "Sharon-Huallpa",
      "sminutosalida": "54",
      "nfecha": 1734095489204,
      "idrdt": "2024-12-13-Sharon-Huallpa",
      "scolaborador": "Sharon Huallpa"
    },
    {
      "ndia": 348,
      "leditable": true,
      "sfecha": "2024-12-13",
      "sminutosalida": "53",
      "nfecha": 1734095489204,
      "sminutoingreso": "58",
      "idrdt": "2024-12-13-Shaunny-Fernandez",
      "idcolaborador": "Shaunny-Fernandez",
      "shoraingreso": "07",
      "shorasalida": "16",
      "scolaborador": "Shaunny Fernandez",
      "nsemana": 50
    },
    {
      "scolaborador": "Yuliana Alvarez Calderón",
      "shoraingreso": "08",
      "ndia": 348,
      "nfecha": 1734095489204,
      "nsemana": 50,
      "idcolaborador": "Yuliana-Alvarez",
      "leditable": true,
      "sminutosalida": "04",
      "idrdt": "2024-12-13-Yuliana-Alvarez",
      "shorasalida": "12",
      "sminutoingreso": "23",
      "sfecha": "2024-12-13"
    },
    {
      "idcolaborador": "darlene-ccasa",
      "nsemana": 50,
      "sfecha": "2024-12-13",
      "sminutoingreso": "59",
      "shorasalida": "17",
      "leditable": true,
      "scolaborador": "Darlene Ccasa",
      "shoraingreso": "12",
      "nfecha": 1734095489204,
      "sminutosalida": "06",
      "ndia": 348,
      "idrdt": "2024-12-13-darlene-ccasa"
    },
    {
      "sminutosalida": "--",
      "idrdt": "2024-12-13-elmer-mamani",
      "sfecha": "2024-12-13",
      "leditable": true,
      "idcolaborador": "elmer-mamani",
      "scolaborador": "Elmer Mamani",
      "nsemana": 50,
      "shoraingreso": "--",
      "shorasalida": "--",
      "nfecha": 1734095489204,
      "ndia": 348,
      "sminutoingreso": "--"
    },
    {
      "ndia": 348,
      "shorasalida": "14",
      "shoraingreso": "08",
      "nsemana": 50,
      "sminutosalida": "31",
      "idrdt": "2024-12-13-jannet-mendoza",
      "sminutoingreso": "22",
      "nfecha": 1734095489204,
      "leditable": true,
      "scolaborador": "Jannet Mendoza",
      "sfecha": "2024-12-13",
      "idcolaborador": "jannet-mendoza"
    },
    {
      "ndia": 348,
      "sminutosalida": "32",
      "idcolaborador": "jim-machaca",
      "sminutoingreso": "42",
      "idrdt": "2024-12-13-jim-machaca",
      "shoraingreso": "12",
      "shorasalida": "14",
      "nsemana": 50,
      "scolaborador": "jimena machaca",
      "nfecha": 1734095489204,
      "sfecha": "2024-12-13",
      "leditable": true
    },
    {
      "ndia": 348,
      "nsemana": 50,
      "scolaborador": "Lizbet Silva Guillén",
      "sminutoingreso": "--",
      "idcolaborador": "lizbet-silva",
      "sminutosalida": "--",
      "shorasalida": "--",
      "sfecha": "2024-12-13",
      "idrdt": "2024-12-13-lizbet-silva",
      "nfecha": 1734095489204,
      "leditable": true,
      "shoraingreso": "--"
    },
    {
      "sminutoingreso": "--",
      "idcolaborador": "Angela-Martinez",
      "idrdt": "2024-12-14-Angela-Martinez",
      "leditable": true,
      "shorasalida": "--",
      "scolaborador": "Angela Martinez",
      "ndia": 349,
      "nfecha": 1734188674168,
      "shoraingreso": "--",
      "nsemana": 50,
      "sminutosalida": "--",
      "sfecha": "2024-12-14"
    },
    {
      "idrdt": "2024-12-14-Angelly-Castillo",
      "scolaborador": "Angelly Castillo",
      "leditable": true,
      "sfecha": "2024-12-14",
      "shorasalida": "--",
      "sminutosalida": "--",
      "nsemana": 50,
      "idcolaborador": "Angelly-Castillo",
      "sminutoingreso": "--",
      "shoraingreso": "--",
      "ndia": 349,
      "nfecha": 1734188674168
    },
    {
      "leditable": true,
      "ndia": 349,
      "nfecha": 1734188674168,
      "sfecha": "2024-12-14",
      "shorasalida": "--",
      "sminutosalida": "--",
      "scolaborador": "Camila Arnica",
      "idcolaborador": "Camila-Arnica",
      "shoraingreso": "--",
      "nsemana": 50,
      "idrdt": "2024-12-14-Camila-Arnica",
      "sminutoingreso": "--"
    },
    {
      "sminutosalida": "--",
      "shoraingreso": "--",
      "idcolaborador": "Christopher-Guzman",
      "shorasalida": "--",
      "sminutoingreso": "--",
      "ndia": 349,
      "scolaborador": "Christopher Guzman",
      "nsemana": 50,
      "sfecha": "2024-12-14",
      "leditable": true,
      "nfecha": 1734188674168,
      "idrdt": "2024-12-14-Christopher-Guzman"
    },
    {
      "leditable": true,
      "sminutosalida": "--",
      "sfecha": "2024-12-14",
      "scolaborador": "Crishtian Paucar",
      "nsemana": 50,
      "idcolaborador": "Crishtian-Paucar",
      "ndia": 349,
      "nfecha": 1734188674168,
      "idrdt": "2024-12-14-Crishtian-Paucar",
      "sminutoingreso": "--",
      "shoraingreso": "--",
      "shorasalida": "--"
    },
    {
      "sfecha": "2024-12-14",
      "sminutoingreso": "--",
      "shorasalida": "--",
      "scolaborador": "Eduardo Soto",
      "shoraingreso": "--",
      "nsemana": 50,
      "idcolaborador": "Edu-Soto",
      "leditable": true,
      "sminutosalida": "--",
      "ndia": 349,
      "nfecha": 1734188674168,
      "idrdt": "2024-12-14-Edu-Soto"
    },
    {
      "nfecha": 1734188674168,
      "nsemana": 50,
      "sfecha": "2024-12-14",
      "sminutosalida": "--",
      "leditable": true,
      "shoraingreso": "--",
      "ndia": 349,
      "shorasalida": "--",
      "idrdt": "2024-12-14-Esmeralda-Aslla",
      "idcolaborador": "Esmeralda-Aslla",
      "sminutoingreso": "--",
      "scolaborador": "Esmeralda Aslla"
    },
    {
      "nsemana": 50,
      "sminutosalida": "--",
      "sminutoingreso": "--",
      "scolaborador": "Fabiola Mayta",
      "leditable": true,
      "sfecha": "2024-12-14",
      "nfecha": 1734188674168,
      "idrdt": "2024-12-14-Fabi-Mayta",
      "shorasalida": "--",
      "idcolaborador": "Fabi-Mayta",
      "shoraingreso": "--",
      "ndia": 349
    },
    {
      "idcolaborador": "Jenny-Perez",
      "shorasalida": "--",
      "ndia": 349,
      "shoraingreso": "--",
      "nfecha": 1734188674168,
      "sminutoingreso": "--",
      "nsemana": 50,
      "sfecha": "2024-12-14",
      "leditable": true,
      "scolaborador": "Jenny Perez",
      "sminutosalida": "--",
      "idrdt": "2024-12-14-Jenny-Perez"
    },
    {
      "scolaborador": "Marcos Carbajal",
      "sfecha": "2024-12-14",
      "shorasalida": "--",
      "leditable": true,
      "idrdt": "2024-12-14-Marcos-Carbajal",
      "sminutosalida": "--",
      "ndia": 349,
      "nsemana": 50,
      "shoraingreso": "--",
      "sminutoingreso": "--",
      "nfecha": 1734188674168,
      "idcolaborador": "Marcos-Carbajal"
    },
    {
      "idrdt": "2024-12-14-Maria-Rosado",
      "nsemana": 50,
      "ndia": 349,
      "nfecha": 1734188674168,
      "shoraingreso": "--",
      "shorasalida": "--",
      "sfecha": "2024-12-14",
      "leditable": true,
      "sminutoingreso": "--",
      "sminutosalida": "--",
      "idcolaborador": "Maria-Rosado",
      "scolaborador": "Maria Rosado"
    },
    {
      "idrdt": "2024-12-14-Mil-Lazo",
      "sfecha": "2024-12-14",
      "nsemana": 50,
      "ndia": 349,
      "sminutoingreso": "--",
      "leditable": true,
      "idcolaborador": "Mil-Lazo",
      "shorasalida": "--",
      "sminutosalida": "--",
      "nfecha": 1734188674168,
      "scolaborador": "Mil Lazo",
      "shoraingreso": "--"
    },
    {
      "idcolaborador": "Nicole-Cardenas",
      "shorasalida": "--",
      "idrdt": "2024-12-14-Nicole-Cardenas",
      "shoraingreso": "--",
      "ndia": 349,
      "sminutoingreso": "--",
      "nfecha": 1734188674168,
      "sminutosalida": "--",
      "leditable": true,
      "sfecha": "2024-12-14",
      "scolaborador": "Nicole Cardenas",
      "nsemana": 50
    },
    {
      "idcolaborador": "Sebastian-Rodriguez",
      "shorasalida": "--",
      "sminutosalida": "--",
      "ndia": 349,
      "scolaborador": "Sebastian Rodriguez",
      "idrdt": "2024-12-14-Sebastian-Rodriguez",
      "sminutoingreso": "--",
      "leditable": true,
      "shoraingreso": "--",
      "nsemana": 50,
      "sfecha": "2024-12-14",
      "nfecha": 1734188674168
    },
    {
      "nsemana": 50,
      "sfecha": "2024-12-14",
      "idcolaborador": "Sharon-Huallpa",
      "nfecha": 1734188674168,
      "sminutosalida": "--",
      "leditable": true,
      "shoraingreso": "--",
      "shorasalida": "--",
      "ndia": 349,
      "sminutoingreso": "--",
      "scolaborador": "Sharon Huallpa",
      "idrdt": "2024-12-14-Sharon-Huallpa"
    },
    {
      "nsemana": 50,
      "sminutosalida": "--",
      "scolaborador": "Shaunny Fernandez",
      "idrdt": "2024-12-14-Shaunny-Fernandez",
      "sfecha": "2024-12-14",
      "sminutoingreso": "--",
      "shoraingreso": "--",
      "nfecha": 1734188674168,
      "shorasalida": "--",
      "leditable": true,
      "ndia": 349,
      "idcolaborador": "Shaunny-Fernandez"
    },
    {
      "sminutoingreso": "--",
      "shorasalida": "--",
      "sfecha": "2024-12-14",
      "nfecha": 1734188674168,
      "nsemana": 50,
      "shoraingreso": "--",
      "idrdt": "2024-12-14-Yuliana-Alvarez",
      "leditable": true,
      "ndia": 349,
      "sminutosalida": "--",
      "scolaborador": "Yuliana Alvarez Calderón",
      "idcolaborador": "Yuliana-Alvarez"
    },
    {
      "ndia": 349,
      "idcolaborador": "darlene-ccasa",
      "leditable": true,
      "sminutosalida": "--",
      "shorasalida": "--",
      "shoraingreso": "--",
      "nsemana": 50,
      "sminutoingreso": "--",
      "scolaborador": "Darlene Ccasa",
      "nfecha": 1734188674168,
      "idrdt": "2024-12-14-darlene-ccasa",
      "sfecha": "2024-12-14"
    },
    {
      "idrdt": "2024-12-14-elmer-mamani",
      "idcolaborador": "elmer-mamani",
      "ndia": 349,
      "sfecha": "2024-12-14",
      "scolaborador": "Elmer Mamani",
      "leditable": true,
      "sminutoingreso": "--",
      "nfecha": 1734188674168,
      "shorasalida": "--",
      "nsemana": 50,
      "shoraingreso": "--",
      "sminutosalida": "--"
    },
    {
      "shoraingreso": "--",
      "ndia": 349,
      "sminutoingreso": "--",
      "scolaborador": "Jannet Mendoza",
      "leditable": true,
      "shorasalida": "--",
      "idcolaborador": "jannet-mendoza",
      "sfecha": "2024-12-14",
      "nfecha": 1734188674168,
      "sminutosalida": "--",
      "idrdt": "2024-12-14-jannet-mendoza",
      "nsemana": 50
    },
    {
      "scolaborador": "jimena machaca",
      "ndia": 349,
      "leditable": true,
      "idrdt": "2024-12-14-jim-machaca",
      "idcolaborador": "jim-machaca",
      "nfecha": 1734188674168,
      "shorasalida": "--",
      "nsemana": 50,
      "shoraingreso": "--",
      "sminutosalida": "--",
      "sfecha": "2024-12-14",
      "sminutoingreso": "--"
    },
    {
      "shoraingreso": "--",
      "ndia": 349,
      "sminutosalida": "--",
      "sminutoingreso": "--",
      "idrdt": "2024-12-14-lizbet-silva",
      "nsemana": 50,
      "scolaborador": "Lizbet Silva Guillén",
      "sfecha": "2024-12-14",
      "shorasalida": "--",
      "leditable": true,
      "nfecha": 1734188674168,
      "idcolaborador": "lizbet-silva"
    }
  ];
  lstAsistencias: any[] = [];

  constructor(
    private db: AngularFirestore,
  ) {
  }

  mergear() {
    this.lstColaboradores.forEach(colaborador => {
      let tiempoOficina = 0;
      this.lstRdts.filter(rdt => rdt.idcolaborador == colaborador.id)
        .filter(rdt => {
          let lok = true;
          if (rdt.shoraingreso == '--') lok = false;
          if (rdt.sminutoingreso == '--') lok = false;
          if (rdt.shorasalida == '--') lok = false;
          if (rdt.sminutosalida == '--') lok = false;
          return lok;
        }).forEach(rdt => {
          let ingreso = Number(rdt.shoraingreso) * 60 + Number(rdt.sminutoingreso);
          let salida = Number(rdt.shorasalida) * 60 + Number(rdt.sminutosalida);
          let tiempo = salida - ingreso;
          tiempoOficina = tiempoOficina + tiempo;
        });
      this.lstAsistencias.push({
        idcolaborador: colaborador.id,
        snombre: colaborador.snombre,
        ntiempo: tiempoOficina,
      })
    });
  }

  subirNuevoExp() {
    this.db.collection('expedientes').doc('E000921').set({
      "idExpediente": "E000921",
      "clase": "PROVISIONAL",
      "numero": "DENUNCIA-RUTH-MARROQUIN",
      "especialidad": "PENAL",
      "nivelIter": 0,
      "demandante": "RUTH ELENA MARROQUIN ROJAS DE CHAVEZ",
      "demandado": "JUAN YURO VALVERDE MALAGA",
      "materia": "ABUSO DE DOCUMENTO EN BLANCO",
      "juzgado": "-",
      "prioridad": "MEDIA",
      "tieneContrato": false,
      "fechaInicio": "10/01/2024",
      "codigo": null,
      "observaciones": "",
      "estado": "EN PROCESO",
      "motivoFinalizacion": null,
      "fechaCreacion": 1737581785859,
      "numeroCasacion": null,
      "numeroCautelar": null,
      "carpetaFiscal": null,
      "salaCasacion": null
    })
  }

}
